### ISSUE TITLE
Definiation of Compression Ratio

### ISSUE THREAD

**Issue by I-Good-Vegetable** [shubhamchandak94/LFZip#4]
Hi,

I'm wondering how the Compression Ratio is defined? Many thanks indeed!
Currently I'm assuming CR = size of original data file (.npz) / size of compressed file (.npz)
Is it correct?

**Comment by shubhamchandak94** [comment]
Yes, that's almost right. In the paper, I think I used 4*length of series (bytes) as the numerator which should be size of original data file (.npz) for 32 bit float (except for numpy headers). The denominator will have lfzip format, not npz.

**Comment by I-Good-Vegetable** [comment]
Got it! Much appreciated!
