### ISSUE TITLE
march=native not supported for all architectures.

### ISSUE THREAD

**Issue by francescotaurone** [shubhamchandak94/LFZip#6]
In install_macos.sh, the flag -march for the clang compiler doesn't work on all architectures.

In order to make it work on my m1, I had to substitute it with -mcpu=apple-m1, resulting in the command

g++ nlms_helper.cpp -std=c++11 -o nlms_helper.out -Wall -O3 -mcpu=apple-m1

**Comment by shubhamchandak94** [comment]
thanks for the note, I have added this to the README now.
